# Template docker-push

# This template allows you to build and push your docker image to a Docker Hub account.
# The workflow allows running tests, code linting and security scans on feature branches (as well as master).
# The docker image will be validated and pushed to the docker registry after the code is merged to master.

# Prerequisites: $DOCKERHUB_USERNAME, $DOCKERHUB_PASSWORD setup as deployment variables

image: atlassian/default-image:2

definitions:
  services:
    docker:
      memory: 6144

pipelines:
  branches:
    master:
      - step:
          size: 2x
          name: Building Docker Image
          script:
            - IMAGE_NAME=$BITBUCKET_REPO_SLUG
            - docker build . --file Dockerfile --tag ${IMAGE_NAME}
            - docker save ${IMAGE_NAME} --output "${IMAGE_NAME}.tar"
          services:
            - docker
          caches:
            - docker
          artifacts:
            - "*.tar"
      - step:
          size: 2x
          name: Uploading Docker image to DockerHub
          script:
            - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            - IMAGE_NAME=$BITBUCKET_REPO_SLUG
            - docker load --input "${IMAGE_NAME}.tar"
            - VERSION="build-${BITBUCKET_BUILD_NUMBER}-${BITBUCKET_BRANCH}"
            - IMAGE="rusas888/${IMAGE_NAME}"
            - docker tag "${IMAGE_NAME}" "${IMAGE}:${VERSION}"
            - docker push "${IMAGE}:${VERSION}"
          services:
            - docker
      - step:
          size: 2x
          name: Deploy to production
          trigger: manual
          deployment: production
          script:
            - IMAGE="rusas888/$BITBUCKET_REPO_SLUG:build-${BITBUCKET_BUILD_NUMBER}-${BITBUCKET_BRANCH}"
            - EVIRONMENT="production"
            - sed -i "s|{{image}}|${IMAGE}|g" deployment.yml
            - sed -i "s|{{environment}}|${EVIRONMENT}|g" deployment.yml
            - pipe: atlassian/kubectl-run:1.3.3
              variables:
                KUBE_CONFIG: $KUBE_CONFIG
                KUBECTL_COMMAND: 'apply'
                RESOURCE_PATH: 'deployment.yml'
