apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing
spec:
  selector:
    matchLabels:
      app: landing
  replicas: 1
  template:
    metadata:
      labels:
        app: landing
    spec:
      nodeSelector:
        doks.digitalocean.com/node-pool: pool-2
      containers:
        - name: landing
          image: {{image}}
      imagePullSecrets:
        - name: dockerhubkey
