apiVersion: apps/v1
kind: Deployment
metadata:
  name: ss-tap-web
spec:
  selector:
    matchLabels:
      app: ss-tap-web
  replicas: 1
  template:
    metadata:
      labels:
        app: ss-tap-web
    spec:
      nodeSelector:
        doks.digitalocean.com/node-pool: pool-2
      containers:
        - name: ss-tap-web
          image: {{image}}
      imagePullSecrets:
        - name: dockerhubkey
